# -*- coding: utf-8 -*-
"""Caja de Ahorros Backend

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YJDL9Phu0oz70N2eKULFGFSrJGwRr4H-
"""

import os
import datetime
from decimal import Decimal
from typing import List
from dotenv import load_dotenv
from fastapi import FastAPI, Depends, HTTPException, status
from pydantic import BaseModel, Field
from sqlalchemy import String, Numeric, ForeignKey, DateTime, select
from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine, async_sessionmaker
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship

# Cargar variables de entorno
load_dotenv()
DATABASE_URL = os.getenv("DATABASE_URL")

engine = create_async_engine(DATABASE_URL, echo=True)
AsyncSessionLocal = async_sessionmaker(bind=engine, class_=AsyncSession, expire_on_commit=False)

class Base(DeclarativeBase):
    pass

# --- MODELOS ---
class Socio(Base):
    __tablename__ = "socios"
    id: Mapped[int] = mapped_column(primary_key=True, index=True)
    cedula: Mapped[str] = mapped_column(String(10), unique=True, index=True, nullable=False)
    nombre: Mapped[str] = mapped_column(String(50), nullable=False)
    apellido: Mapped[str] = mapped_column(String(50), nullable=False)
    email: Mapped[str] = mapped_column(String(100), unique=True, nullable=False)
    fecha_registro: Mapped[datetime.datetime] = mapped_column(DateTime, default=datetime.datetime.utcnow)
    cuentas: Mapped[List["Cuenta"]] = relationship("Cuenta", back_populates="socio", cascade="all, delete-orphan")

class Cuenta(Base):
    __tablename__ = "cuentas"
    id: Mapped[int] = mapped_column(primary_key=True, index=True)
    numero_cuenta: Mapped[str] = mapped_column(String(20), unique=True, index=True, nullable=False)
    tipo_cuenta: Mapped[str] = mapped_column(String(30), default="Ahorro")
    saldo: Mapped[Decimal] = mapped_column(Numeric(12, 2), default=Decimal("0.00"))
    estado: Mapped[str] = mapped_column(String(20), default="Activa")   
    socio_id: Mapped[int] = mapped_column(ForeignKey("socios.id"), nullable=False)
    socio: Mapped["Socio"] = relationship("Socio", back_populates="cuentas")
    asientos: Mapped[List["Asiento"]] = relationship("Asiento", back_populates="cuenta", cascade="all, delete-orphan")

class Asiento(Base):
    __tablename__ = "asientos"
    id: Mapped[int] = mapped_column(primary_key=True, index=True)
    cuenta_id: Mapped[int] = mapped_column(ForeignKey("cuentas.id"), nullable=False)
    tipo_movimiento: Mapped[str] = mapped_column(String(10), nullable=False)
    monto: Mapped[Decimal] = mapped_column(Numeric(12, 2), nullable=False)
    descripcion: Mapped[str] = mapped_column(String(255), nullable=True)
    timestamp: Mapped[datetime.datetime] = mapped_column(DateTime, default=datetime.datetime.utcnow)
    cuenta: Mapped["Cuenta"] = relationship("Cuenta", back_populates="asientos")

# --- SCHEMAS ---
class DepositoRequest(BaseModel):
    idSocio: int
    monto: float
    descripcion: str

class DepositoResponse(BaseModel):
    mensaje: str
    idTransaccion: int
    nuevoSaldo: float

# AGREGA ESTO:
class SaldoResponse(BaseModel):
    idSocio: int
    nombre: str
    saldoDisponible: float

class SolicitudCreditoRequest(BaseModel):
    idSocio: int
    monto: float
    descripcion: str

class SolicitudCreditoResponse(BaseModel):
    idSolicitud: int
    mensaje: str
    estado: str

# --- FASTAPI APP ---
app = FastAPI(title="Sistema de Cajas de Ahorro API")

async def get_db():
    async with AsyncSessionLocal() as session:
        try:
            yield session
            await session.commit()
        except Exception:
            await session.rollback()
            raise
        finally:
            await session.close()

@app.post("/api/transacciones/deposito", response_model=DepositoResponse)
async def registrar_deposito(payload: DepositoRequest, db: AsyncSession = Depends(get_db)):
    socio = (await db.execute(select(Socio).where(Socio.id == payload.idSocio))).scalar_one_or_none()
    if not socio: raise HTTPException(status_code=404, detail="Socio no encontrado")

    cuenta = (await db.execute(select(Cuenta).where(Cuenta.socio_id == payload.idSocio, Cuenta.estado == "Activa"))).scalar_one_or_none()
    if not cuenta: raise HTTPException(status_code=400, detail="Sin cuenta activa")

    monto_decimal = Decimal(str(payload.monto))
    nuevo_asiento = Asiento(cuenta_id=cuenta.id, tipo_movimiento="CREDITO", monto=monto_decimal, descripcion=payload.descripcion)
    db.add(nuevo_asiento)
    cuenta.saldo += monto_decimal
    db.add(cuenta)
    await db.flush()
    return DepositoResponse(mensaje="Depósito registrado", idTransaccion=nuevo_asiento.id, nuevoSaldo=float(cuenta.saldo))

# ==============================================================================
# INICIALIZACIÓN DE FASTAPI Y DEPENDENCIAS
# ==============================================================================

app = FastAPI(
    title="Sistema de Cajas de Ahorro API",
    description="Servicios backend para la gestión de depósitos, saldos y créditos.",
    version="1.0.0"
)

# Dependencia para inyectar la sesión de la base de datos en los controladores
async def get_db():
    async with AsyncSessionLocal() as session:
        try:
            yield session
            await session.commit()
        except Exception:
            await session.rollback()
            raise
        finally:
            await session.close()


@app.on_event("startup")
async def startup():
    """Crea automáticamente las tablas de la base de datos si no existen."""
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)


# ==============================================================================
# CONTROLADORES / ENDPOINTS (Diseño de API de Anthony implementado)
# ==============================================================================

@app.post(
    "/api/transacciones/deposito",
    response_model=DepositoResponse,
    status_code=status.HTTP_201_CREATED,
    tags=["Transacciones"]
)
async def registrar_deposito(payload: DepositoRequest, db: AsyncSession = Depends(get_db)):
    """
    Permite registrar un depósito financiero en la cuenta de ahorro de un socio
    y actualiza su saldo correspondiente bajo una transacción segura.
    """
    # 1. Buscar si el socio existe
    resultado_socio = await db.execute(select(Socio).where(Socio.id == payload.idSocio))
    socio = resultado_socio.scalar_one_or_none()
    if not socio:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Socio con ID {payload.idSocio} no encontrado"
        )

    # 2. Buscar la cuenta activa del socio
    resultado_cuenta = await db.execute(
        select(Cuenta).where(Cuenta.socio_id == payload.idSocio, Cuenta.estado == "Activa")
    )
    cuenta = resultado_cuenta.scalar_one_or_none()
    if not cuenta:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="El socio no posee ninguna cuenta de ahorro activa registrada"
        )

    # 3. Registrar el Asiento Contable (Partida Doble)
    monto_decimal = Decimal(str(payload.monto))
    nuevo_asiento = Asiento(
        cuenta_id=cuenta.id,
        tipo_movimiento="CREDITO",  # Un depósito incrementa la cuenta
        monto=monto_decimal,
        descripcion=payload.descripcion
    )
    db.add(nuevo_asiento)

    # 4. Actualizar el saldo de la cuenta
    cuenta.saldo += monto_decimal
    db.add(cuenta)

    # Forzar el guardado y refrescar para obtener el ID generado del asiento
    await db.flush()

    return DepositoResponse(
        mensaje="Depósito registrado correctamente",
        idTransaccion=nuevo_asiento.id,
        nuevoSaldo=float(cuenta.saldo)
    )


@app.get(
    "/api/socios/{id}/saldo",
    response_model=SaldoResponse,
    tags=["Socios"]
)
async def consultar_saldo(id: int, db: AsyncSession = Depends(get_db)):
    """
    Obtiene el saldo actual disponible de la cuenta de ahorro de un socio específico.
    """
    # 1. Buscar socio y su cuenta asociada
    resultado = await db.execute(
        select(Socio).where(Socio.id == id)
    )
    socio = resultado.scalar_one_or_none()
    if not socio:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Socio con ID {id} no existe en el sistema"
        )

    resultado_cuenta = await db.execute(
        select(Cuenta).where(Cuenta.socio_id == id)
    )
    cuenta = resultado_cuenta.scalar_one_or_none()
    saldo_disponible = float(cuenta.saldo) if cuenta else 0.0

    return SaldoResponse(
        idSocio=socio.id,
        nombre=f"{socio.nombre} {socio.apellido}",
        saldoDisponible=saldo_disponible
    )


@app.post(
    "/api/creditos/solicitud",
    response_model=SolicitudCreditoResponse,
    status_code=status.HTTP_201_CREATED,
    tags=["Créditos"]
)
async def solicitar_credito(payload: SolicitudCreditoRequest, db: AsyncSession = Depends(get_db)):
    """
    Permite registrar una solicitud formal de crédito para que el socio sea evaluado
    financieramente por la cooperativa o caja de ahorros.
    """
    # Validar si el socio solicitante existe
    resultado = await db.execute(select(Socio).where(Socio.id == payload.idSocio))
    socio = resultado.scalar_one_or_none()
    if not socio:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Socio con ID {payload.idSocio} no registrado"
        )

    # Simulación de ID de solicitud y registro exitoso
    import random
    id_solicitud_generada = random.randint(100, 999)

    return SolicitudCreditoResponse(
        idSolicitud=id_solicitud_generada,
        estado="Pendiente",
        mensaje="Solicitud registrada exitosamente y enviada al comité de riesgos"
    )